### ISSUE TITLE
sleekxmppfs.basexmpp WARNING  fulljid property deprecated. Use boundjid.resource

### ISSUE THREAD

**Issue by jlhunter2008** [wpietri/sucks#82] opened 2019-10-16 03:37 UTC
I keep getting this warning message in homebridge logs when I run a command, for example, sucks clean 10. How do I resolve this?

**Comment by bggardner** [comment] 2020-05-12 16:09
Duplicate of #46

**Closed** 2020-05-25 22:43 UTC
